name: Playwright Electron UI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:  #允许手动触发
jobs:
  test:
    runs-on: self-hosted   # 使用你的 Jetson Runner
    steps:
      - name: 检出最新代码
        uses: actions/checkout@v4

      - name: 安装 Node 依赖
        run: npm ci

      - name: 运行 Playwright 测试
        run: npx playwright test
        env:
          DISPLAY: :0   # 使用真实显示器，确保 Runner 能打开 GUI

#      - name: 上传测试失败产物（截图、录像、Trace）
#        if: failure()
#        uses: actions/upload-artifact@v4
#        with:
#          name: test-results-${{ github.run_id }}
#          path: test-results/
